### ISSUE TITLE
java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter s

### ISSUE THREAD

**Issue by xunyixiangchao** [LRH1993/Eyepetizer-in-Kotlin#17]
java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter s
                                                                                at com.tt.lvruheng.eyepetizer.ui.VideoDetailActivity$ImageViewAsyncTask.onPostExecute(VideoDetailActivity.kt)
                                                                                at com.tt.lvruheng.eyepetizer.ui.VideoDetailActivity$ImageViewAsyncTask.onPostExecute(VideoDetailActivity.kt:180)
                                                                                at android.os.AsyncTask.finish(AsyncTask.java:651)
                                                                                at android.os.AsyncTask.access$500(AsyncTask.java:180)
                                                                                at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                at android.os.Looper.loop(Looper.java:157)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5637)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:746)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:636)

在图片还没有加载的时候，点击进入播放面，会报这个错误。

**Comment by xunyixiangchao** [comment]
![image](https://user-images.githubusercontent.com/7007625/32714081-1764538e-c887-11e7-9157-c6d145902756.png)
网速较差时，这块取到的路径会是个null。
