### ISSUE TITLE
RuntimeException

### ISSUE THREAD

**Issue by mbpz** [LRH1993/Eyepetizer-in-Kotlin#2]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.tt.lvruheng.eyepetizer/com.tt.lvruheng.eyepetizer.ui.SplashActivity}: android.content.res.Resources$NotFoundException: Resource ID #0x7f070058
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2214)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2264)
                                                                              at android.app.ActivityThread.access$600(ActivityThread.java:144)
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1259)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                              at android.os.Looper.loop(Looper.java:137)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5136)
                                                                              at java.lang.reflect.Method.invokeNative(Native Method)
                                                                              at java.lang.reflect.Method.invoke(Method.java:525)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                                                                              at dalvik.system.NativeStart.main(Native Method)
                                                                           Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f070058
                                                                              at android.content.res.Resources.getValue(Resources.java:1118)
                                                                              at android.support.v7.widget.AppCompatDrawableManager.loadDrawableFromDelegates(AppCompatDrawableManager.java:332)
                                                                              at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:197)
                                                                              at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:190)
                                                                              at android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:711)
                                                                              at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:195)
                                                                              at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:81)
                                                                              at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java:131)
                                                                              at android.support.v7.app.AppCompatDelegateImplV9.<init>(AppCompatDelegateImplV9.java:155)
                                                                              at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java:31)
                                                                              at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java:55)
                                                                              at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:205)
                                                                              at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:185)
                                                                              at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:519)
                                                                              at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:71)
                                                                              at com.tt.lvruheng.eyepetizer.ui.SplashActivity.onCreate(SplashActivity.kt:23)
                                                                              at android.app.Activity.performCreate(Activity.java:5133)
                                                                              at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2178)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2264) 
                                                                              at android.app.ActivityThread.access$600(ActivityThread.java:144) 
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1259) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                              at android.os.Looper.loop(Looper.java:137) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5136) 
                                                                              at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                              at java.lang.reflect.Method.invoke(Method.java:525) 
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737) 
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
                                                                              at dalvik.system.NativeStart.main(Native Method)

**Comment by LRH1993** [comment]
可能是手机API适配问题，资源找不到。定位下出现问题的代码。

**Comment by mbpz** [comment]
07-13 11:35:46.727 6008-6008/? D/dalvikvm: Late-enabling CheckJNI
07-13 11:35:46.817 6008-6008/com.tt.lvruheng.eyepetizer I/dalvikvm: Could not find method android.view.Window$Callback.onProvideKeyboardShortcuts, referenced from method android.support.v7.view.WindowCallbackWrapper.onProvideKeyboardShortcuts
07-13 11:35:46.817 6008-6008/com.tt.lvruheng.eyepetizer W/dalvikvm: VFY: unable to resolve interface method 22538: Landroid/view/Window$Callback;.onProvideKeyboardShortcuts (Ljava/util/List;Landroid/view/Menu;I)V
07-13 11:35:46.817 6008-6008/com.tt.lvruheng.eyepetizer D/dalvikvm: VFY: replacing opcode 0x72 at 0x0002
07-13 11:35:46.827 6008-6008/com.tt.lvruheng.eyepetizer W/dalvikvm: VFY: unable to find class referenced in signature (Landroid/view/SearchEvent;)
07-13 11:35:46.827 6008-6008/com.tt.lvruheng.eyepetizer I/dalvikvm: Could not find method android.view.Window$Callback.onSearchRequested, referenced from method android.support.v7.view.WindowCallbackWrapper.onSearchRequested
07-13 11:35:46.827 6008-6008/com.tt.lvruheng.eyepetizer W/dalvikvm: VFY: unable to resolve interface method 22540: Landroid/view/Window$Callback;.onSearchRequested (Landroid/view/SearchEvent;)Z
07-13 11:35:46.827 6008-6008/com.tt.lvruheng.eyepetizer D/dalvikvm: VFY: replacing opcode 0x72 at 0x0002
07-13 11:35:46.827 6008-6008/com.tt.lvruheng.eyepetizer I/dalvikvm: Could not find method android.view.Window$Callback.onWindowStartingActionMode, referenced from method android.support.v7.view.WindowCallbackWrapper.onWindowStartingActionMode
07-13 11:35:46.827 6008-6008/com.tt.lvruheng.eyepetizer W/dalvikvm: VFY: unable to resolve interface method 22544: Landroid/view/Window$Callback;.onWindowStartingActionMode (Landroid/view/ActionMode$Callback;I)Landroid/view/ActionMode;
07-13 11:35:46.827 6008-6008/com.tt.lvruheng.eyepetizer D/dalvikvm: VFY: replacing opcode 0x72 at 0x0002
07-13 11:35:46.827 6008-6008/com.tt.lvruheng.eyepetizer I/dalvikvm: Could not find method android.content.res.TypedArray.getChangingConfigurations, referenced from method android.support.v7.widget.TintTypedArray.getChangingConfigurations
07-13 11:35:46.827 6008-6008/com.tt.lvruheng.eyepetizer W/dalvikvm: VFY: unable to resolve virtual method 634: Landroid/content/res/TypedArray;.getChangingConfigurations ()I
07-13 11:35:46.827 6008-6008/com.tt.lvruheng.eyepetizer D/dalvikvm: VFY: replacing opcode 0x6e at 0x0002
07-13 11:35:46.837 6008-6008/com.tt.lvruheng.eyepetizer I/dalvikvm: Could not find method android.content.res.TypedArray.getType, referenced from method android.support.v7.widget.TintTypedArray.getType
07-13 11:35:46.837 6008-6008/com.tt.lvruheng.eyepetizer W/dalvikvm: VFY: unable to resolve virtual method 656: Landroid/content/res/TypedArray;.getType (I)I
07-13 11:35:46.837 6008-6008/com.tt.lvruheng.eyepetizer D/dalvikvm: VFY: replacing opcode 0x6e at 0x0008
07-13 11:35:46.837 6008-6008/com.tt.lvruheng.eyepetizer W/ResourceType: Failure getting entry for 0x7f070058 (t=6 e=88) in package 0 (error -75)
07-13 11:35:46.837 6008-6008/com.tt.lvruheng.eyepetizer D/AndroidRuntime: Shutting down VM
07-13 11:35:46.837 6008-6008/com.tt.lvruheng.eyepetizer W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x41db2898)

**Comment by LRH1993** [comment]
这一长串，看的头晕。第一个资源问题，我看了下我的代码23行是super.onCreate，不会出问题啊
