### ISSUE TITLE
离线环境读缓存闪退

### ISSUE THREAD

**Issue by ztc464728422** [LRH1993/Eyepetizer-in-Kotlin#8]
08-10 10:40:05.029 29118-29118/com.tt.lvruheng.eyepetizer E/AndroidRuntime: FATAL EXCEPTION: main
                                                                            Process: com.tt.lvruheng.eyepetizer, PID: 29118
                                                                            io.reactivex.exceptions.OnErrorNotImplementedException: HTTP 504 Unsatisfiable Request (only-if-cached)
                                                                                at io.reactivex.internal.functions.Functions$14.accept(Functions.java:229)
                                                                                at io.reactivex.internal.functions.Functions$14.accept(Functions.java:226)
                                                                                at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:72)
                                                                                at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.checkTerminated(ObservableObserveOn.java:276)
                                                                                at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:172)
                                                                                at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
                                                                                at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
                                                                                at android.os.Handler.handleCallback(Handler.java:761)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                at android.os.Looper.loop(Looper.java:156)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:6523)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
                                                                             Caused by: com.jakewharton.retrofit2.adapter.rxjava2.HttpException: HTTP 504 Unsatisfiable Request (only-if-cached)
                                                                                at com.jakewharton.retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:54)
                                                                                at com.jakewharton.retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:37)
                                                                                at com.jakewharton.retrofit2.adapter.rxjava2.CallObservable.subscribeActual(CallObservable.java:43)
                                                                                at io.reactivex.Observable.subscribe(Observable.java:10700)
                                                                                at com.jakewharton.retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
                                                                                at io.reactivex.Observable.subscribe(Observable.java:10700)
                                                                                at io.reactivex.internal.operators.observable.ObservableSubscribeOn$1.run(ObservableSubscribeOn.java:39)
                                                                                at io.reactivex.Scheduler$1.run(Scheduler.java:138)
                                                                                at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:59)
                                                                                at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:51)
                                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
                                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                at java.lang.Thread.run(Thread.java:776)

**Comment by ztc464728422** [comment]
离线情况下，首页一直下拉到未缓存的内容，会闪退，或者离线安装，首次打开时闪退

**Comment by ztc464728422** [comment]
io.reactivex.exceptions.OnErrorNotImplementedException: HTTP 504 Unsatisfiable Request (only-if-cached)

Caused by: com.jakewharton.retrofit2.adapter.rxjava2.HttpException: HTTP 504 Unsatisfiable Request (only-if-cached)

**Comment by ztc464728422** [comment]
在subscribe(onNext);中只处理了onNext,没有处理onError导致的。如果subscribe(onNext，error);这样处理的，就没有异常了.
